schemaName: sbtest

dataSources:
  write_ds:
    url: jdbc:postgresql://10.0.0.1:5432/sbtest?serverTimezone=UTC&useSSL=false
    username: postgres
    password:
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 128
    minPoolSize: 128
    maintenanceIntervalMilliseconds: 30000

  read_ds:
    url: jdbc:postgresql://10.0.0.1:5432/sbtest?serverTimezone=UTC&useSSL=false
    username: postgres
    password:
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 128
    minPoolSize: 128
    maintenanceIntervalMilliseconds: 30000

rules:
- !READWRITE_SPLITTING
  dataSources:
    pr_ds:
      writeDataSourceName: write_ds
      readDataSourceNames: [read_ds]